### ISSUE TITLE
Can't build after updating to 8

### ISSUE THREAD

**Issue by clundberg1** [meltedspark/angular-builders#329]
**Describe the bug**
After updating Angular to version 8 and the library to 8.0.1, it breaks completely when trying to build.

angular.json
```
...
"architect": {
    ...
    "build": {
        "builder": "@angular-builders/custom-webpack:browser",
        "options": {
            "customWebpackConfig": {
                 "path": "./webpack.config.js",
                 "mergeStrategies": { "externals": "replace" }
             },
             ...
        }
     }
}
```
webpack.config.js
```
const MomentLocalesPlugin = require('moment-locales-webpack-plugin');

module.exports = {
    plugins: [
        new MomentLocalesPlugin({
            localesToKeep: ['en'],
        }),
    ],
};
```

After running ng build --prod, I get the following error:

```
architect_1.createBuilder is not a function
TypeError: architect_1.createBuilder is not a function

```

If I return it to Angular's builder, it builds correctly.

**Comment by meltedspark** [comment]
Make sure you use Angular CLI 8. The latest version of Angular builders is incompatible with Angular CLI 7 and earlier versions.

**Comment by clundberg1** [comment]
Like I said, I already updated to version 8

Angular CLI: 8.0.1
Node: 12.3.1
OS: win32 x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.8
@angular-devkit/build-angular      0.800.1
@angular-devkit/build-optimizer    0.800.1
@angular-devkit/build-webpack      0.13.8
@angular-devkit/core               7.3.8
@angular-devkit/schematics         8.0.1
@angular/cdk                       7.3.7
@angular/cli                       8.0.1
@angular/flex-layout               7.0.0-beta.24
@angular/material                  7.3.7
@angular/material-moment-adapter   7.3.7
@ngtools/webpack                   8.0.1
@schematics/angular                8.0.1
@schematics/update                 0.800.1
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.29.0

**Comment by meltedspark** [comment]
All the `@angular-devkit` packages versions should be greater than or equal to `0.800.0`. You have a mix.

**Comment by clundberg1** [comment]
Did your packages update correctly? I don't understand why mine haven't. I've uninstalled the cli, deleted node_modules, reinstalled everything, and the versions are still the same.

**Comment by meltedspark** [comment]
You have a lot of explicit dependencies that 8n general you shouldn't have. Like `architect`, `build-optimizer`, `build-webpack` etc. All these are Angular CLI dependencies and are installed with it. Maybe that's the problem. In any case, the moment you'll update your dependencies versions everything will work.
