### ISSUE TITLE
TypeScript diagnostics error with jest builder v7.4.1

### ISSUE THREAD

**Issue by wkiril** [meltedspark/angular-builders#285]
**Describe the bug**
After upgrade to v7.4.1 of the jest builder and using jest@^24.5.0 I get this error from jest:

`TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
    error TS6053: File 'src/test.ts' not found.`

Also the jest typing were gone but I've fixed that by manually installing @types/jest

**To Reproduce**
1. npm i @angular-builders/jest on an existing project

**Expected behavior**
no configuration or typescript related errors

**Builder:**
 - jest
 - 7.4.1

**Comment by meltedspark** [comment]
Thanks for the report. Would you mind providing a repo with a minimal reproduction?

**Comment by wkiril** [comment]
yes, I will try

**Comment by wkiril** [comment]
I'm not able to reproduce this with a new repo but found that the problem is having:
`
  "files": [
    "test.ts",
    "polyfills.ts"
  ],
`
in `tsconfig.spec.json` where `test.ts` is removed. but with the new repo - same `tsconfig.spec.json` with the missing file the error is not shown. I also need to add `@types/jest` in the existing project but it works without it in the new repo.

so I guess I've misconfigured something or am in a dependency hell

**Comment by meltedspark** [comment]
So it's not a bug, it is an expected error. You're getting this error because you have `test.ts` in `files` (which tells TS compile to compile this file) but this file doesn't exist.  
The real problem here is that it's mentioned in docs that you should remove the file but it's not mentioned that you have to remove it from `files` array.  
Ideally all these steps should be done with schematics (automatically when you install `@angular-builders/jest`) but unfortunately I'm just not getting to it.  
But yes, it should at least appear in the README. Want to create a PR for this?

**Comment by wkiril** [comment]
yes, I'd like to. but I still don't understand why it is working for a new project and the `test.ts` is still in the files array

**Comment by meltedspark** [comment]
Did you remove the actual file in the new project?

**Comment by wkiril** [comment]
yes

**Comment by meltedspark** [comment]
That's interesting. Unfortunately without the reproduction I can't figure out the problem. Any chance you can start with your repo and make a reproduction from it? Just leave the necessary pieces and remove the rest so I could take a look?

**Comment by wkiril** [comment]
I think I found the cause for this. I didn't notice this before:

npm WARN @angular-builders/jest@7.4.1 requires a peer of @angular-devkit/build-angular@>=0.13.2 but none is installed. You must install peer dependencies yourself.

after manually installing the dependency it works as expected

**Comment by meltedspark** [comment]
If you had to manually install the dependency it probably means that you're on outdated version of Angular, I'd check it.  
The issue can be closed?

**Comment by wkiril** [comment]
I'm on 6.1.10. yes, I think it can be closed
